# Generated by Django 3.2.3 on 2021-07-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=1234)),
                ('enabled', models.BooleanField(default=True)),
                ('secure', models.BooleanField(default=True)),
            ],
        ),
    ]
