# Generated by Django 3.2.3 on 2021-07-11 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_gateway"),
    ]

    operations = [
        migrations.AddField(
            model_name="gateway",
            name="admin_port",
            field=models.IntegerField(default=1235),
        ),
        migrations.AlterField(
            model_name="user",
            name="active_config",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="app.config",
            ),
        ),
    ]
