# Generated by Django 3.2.3 on 2021-06-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210605_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_connection_gateway',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
