# Generated by Django 3.2.3 on 2021-06-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_custom_connection_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_connection_gateway_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
